name: Java CI with Maven

on:
  push:
    branches: [master]
    paths:
      - "**"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Push to production
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWD }}
          port: ${{ secrets.SSH_PORT }}
          source: "target"
          target: "/root/databaseProject"
      - name: exec restart shell
        uses: tarunjangra/ssh-remote-cmd@v1
        with:
          command: |
            cd /root
            ./restartService.sh
          host: ${{ secrets.SSH_HOST }}
          user: root
          pass: ${{ secrets.SSH_PASSWD }}
